# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: FortifyOnDemandStatic@8
  inputs:
    FortifyProjects: '$(Pipeline.Workspace)/s'
    FodConnection: 'FoD_AMS_API'
    ReleaseOptions: '0'
    ReleaseId: 99396
    EntitlementSelection: '0'
    Entitlement: 2225
    EntitlementPreference: '0'
    OverrideScanSettings: '2'
    InProgressScanActionType: '1'
    RemediationScanPreference: '0'
    BuildType: 'mvn'
    PollingInterval: 0
    PolicyFailAction: '0'