# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

################################################################################################################################################
# Fortify lets you build secure software fast with an appsec platform that automates testing throughout the DevSecOps pipeline. Fortify static,#
# dynamic, interactive, and runtime security testing is available on premises or as a service. To learn more about Fortify, start a free trial #
# or contact our sales team, visit microfocus.com/appsecurity.                                                                                 #
#                                                                                                                                              #
# Use this workflow template as a basis for integrating Fortify on Demand Static Application Security Testing(SAST) into your GitHub workflows.#
# This template demonstrates the steps to prepare the code+dependencies, initiate a scan, download results once complete and import into       #
# GitHub Security Code Scanning Alerts. Existing customers should review inputs and environment variables below to configure scanning against  #
# an existing application in your Fortify on Demand tenant. Additional information is available in the comments throughout the workflow, the   #
# documentation for the Fortify actions used, and the Fortify on Demand / ScanCentral Client product documentation. If you need additional     #
# assistance with configuration, feel free to create a help ticket in the Fortify on Demand portal.                                            #
################################################################################################################################################

name: Fortify on Demand Scan

# TODO: Customize trigger events based on your DevSecOps processes and typical FoD SAST scan time
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '44 8 * * 1'

jobs:     
    - name: Run FoD SAST Scan
      id: "perform_fod_scan"
      continue-on-error: true         
      uses: fortify/github-action@v1
      with:
          sast-scan: true
      env:
          FOD_TENANT: abel
          FOD_USER: abelfodtest
          FOD_PASSWORD: MTd6TVF3U1k0T3NZVGxmNER5NURqej1yLVJqK2dw0
          FOD_RELEASE_ID: 1087399
          FOD_URL: https://ams.fortify.com
          FOD_API_URL: https://api.ams.fortify.com
          FOD_UPLOADER_OPTS: "-ep 3 -pp 0 -I 1 -apf"
          FOD_UPLOADER_NOTES: 'Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'

################################################################## BLJ Added
    -
      name: "Set output"
      id: results
      run: echo "results=finished" >> $GITHUB_OUTPUT
